name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Set up node modules
      run: npm ci

    - name: Execute tests
      run: npm run test
      env:
        CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

    - name: Build action
      run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./dist